iaas_settings:
  disk_pools:
    - name: database_disks
      <<: (( merge ))
      cloud_properties:
        <<: (( merge ))
        type: gp2
  stemcell:
    name: (( merge ))
    version: (( merge ))
  subnet_configs:
    - name: diego1
      subnets: (( merge ))
    - name: diego-vizzini
      subnets: (( merge || nil ))
    - name: diego-benchmarks
      subnets: (( merge || nil ))
  compilation_cloud_properties: (( merge ))
  resource_pool_cloud_properties:
    - name: access_z1
      cloud_properties:
        <<: (( merge ))
        instance_type: m3.medium
    - name: brain_z1
      cloud_properties:
        <<: (( merge ))
        instance_type: m3.medium
    - name: cc_bridge_z1
      cloud_properties:
        <<: (( merge ))
        instance_type: m3.medium
    - name: cell_z1
      cloud_properties:
        <<: (( merge ))
        instance_type: r3.xlarge
    - name: colocated_z1
      cloud_properties:
        <<: (( merge ))
        instance_type: r3.xlarge
    - name: database_z1
      cloud_properties:
        <<: (( merge ))
        instance_type: m3.large
    - name: route_emitter_z1
      cloud_properties:
        <<: (( merge ))
        instance_type: m3.medium
    - name: errand
      cloud_properties:
        <<: (( merge || nil ))
        instance_type: m3.medium
