iaas_settings:
  stemcell:
    name: (( merge ))
    version: (( merge ))
  subnet_configs:
    - name: diego1_windows
      subnets: (( merge ))
  compilation_cloud_properties: (( merge ))
  resource_pool_cloud_properties:
    - name: cell_windows_z1
      cloud_properties: (( merge ))
