---
meta: (( merge ))

vpc:
  cidr: (( meta.vpc.base ".0.0/16" ))

dns:
  - (( meta.vpc.base ".0.2" ))
  - (( meta.vpc.base ".0.6" ))

default_subnets:
  - <<: (( merge ))

  - name: BOSHZ1
    cidr: (( meta.vpc.base ".0.0/24" ))
    availability_zone: (( meta.availability_zones.[0] ))
    nat:
      ip: (( meta.vpc.base ".0.10" ))

  - name: CFELBZ1
    cidr: (( meta.vpc.base ".1.0/24" ))
    availability_zone: (( meta.availability_zones.[0] ))

  - name: SSHProxyELBZ1
    cidr: (( meta.vpc.base ".15.0/24" ))
    availability_zone: (( meta.availability_zones.[0] ))

  - name: CFZ1
    cidr: (( meta.vpc.base ".2.0/24" ))
    availability_zone: (( meta.availability_zones.[0] ))

  - name: DiegoZ1
    cidr: (( meta.vpc.base ".5.0/24" ))
    availability_zone: (( meta.availability_zones.[0] ))

  - name: Errands
    cidr: (( meta.vpc.base ".10.0/24" ))
    availability_zone: (( meta.availability_zones.[0] ))

  - name: MySQLZ1
    cidr: (( meta.vpc.base ".11.0/24" ))
    availability_zone: (( meta.availability_zones.[0] ))

  - name: DiegoWindowsZ1
    cidr: (( meta.vpc.base ".18.0/24" ))
    availability_zone: (( meta.availability_zones.[0] ))


load_balancers:
  - name: CFELB
    listeners:
      - protocol: http
        port: 80
      - protocol: https
        port: 443
        destination_protocol: http
        destination_port: 80
        ssl_certificate_id: (( .ServerCertificate.ServerCertificateMetadata.Arn ))
      - protocol: ssl
        port: 4443
        destination_protocol: tcp
        destination_port: 80
        ssl_certificate_id: (( .ServerCertificate.ServerCertificateMetadata.Arn ))

  - name: SSHProxyELB
    listeners:
      - protocol: tcp
        port: 2222
        destination_protocol: tcp
        destination_port: 2222

ServerCertificate: (( merge ))
