iaas_settings:
  stemcell:
    name: bosh-aws-xen-hvm-windows-stemcell-go_agent
    version: latest
  subnet_configs:
    - name: diego1_windows
      subnets:
        - range:    (( Resources.SubnetCIDR.DiegoWindowsZ1 ))
          reserved: (( [Resources.SubnetOctets.DiegoWindowsZ1.[2] ".2 - " Resources.SubnetOctets.DiegoWindowsZ1.[2] ".9"] ))
          static:   (( [Resources.SubnetOctets.DiegoWindowsZ1.[2] ".10 - " Resources.SubnetOctets.DiegoWindowsZ1.[2] ".63"] ))
          gateway:  (( Resources.SubnetOctets.DiegoWindowsZ1.[2] ".1" ))
          dns:      (( [Resources.SubnetOctets.DiegoWindowsZ1.[1] ".0.2"] ))
          cloud_properties:
            security_groups: (( [Resources.SecurityGroupName.Internal] ))
            subnet: (( Resources.Subnet.DiegoWindowsZ1 ))
  compilation_cloud_properties:
    instance_type: c3.large
    availability_zone: (( Resources.SubnetAvailabilityZone.DiegoWindowsZ1 ))
    root_disk:
      size: 10_000
  resource_pool_cloud_properties:
    - name: cell_windows_z1
      cloud_properties:
        instance_type: (( instance_types.cell_windows ))
        availability_zone: (( Resources.SubnetAvailabilityZone.DiegoWindowsZ1 ))
        root_disk:
          size: (( disk_size.cell_windows ))


instance_types:
  cell_windows: (( merge || "r3.xlarge" ))
disk_size:
  cell_windows: (( merge || 10000 ))
Resources:
  Subnet:
    DiegoWindowsZ1: (( merge ))
  SubnetAvailabilityZone:
    DiegoWindowsZ1: (( merge ))
  SubnetOctets:
    DiegoWindowsZ1: (( merge ))
  SubnetCIDR:
    DiegoWindowsZ1: (( merge ))
  SecurityGroupName:
    Internal: (( merge ))
  LoadBalancer:
    SSHProxyELB: (( merge ))
